export const CHATBOT_SCOPE = {
  allowedTopics: [
    'easy lane',
    'tms',
    'transportation management',
    'fms',
    'fleet management',
    'bill discounting',
    'booking',
    'trips',
    'dispatch',
    'pod',
    'invoice',
    'payments',
    'finance',
    'vendor',
    'driver',
    'customer',
    'admin',
    'vendor portal',
    'driver workflows',
    'customer workflows',
    '3pl',
    'enterprise',
    'logistics operations',
    'easy lane website',
    'easy lane features',
    'easy lane modules',
    'easy lane demo',
    'contact support',
    'privacy policy',
    'terms',
    'policies related to easy lane',
  ],
  topicKeywords: [
    'easy lane',
    'easylane',
    'ईज़ी लेन',
    'इजी लेन',
    'tms',
    'टीएमएस',
    'transport',
    'transportation',
    'logistics',
    'fleet',
    'fms',
    'vehicle',
    'truck',
    'trip',
    'booking',
    'dispatch',
    'pod',
    'proof of delivery',
    'invoice',
    'payment',
    'finance',
    'bill discounting',
    'vendor',
    'driver',
    'customer',
    'admin',
    'portal',
    '3pl',
    'enterprise',
    'demo',
    'support',
    'privacy',
    'policy',
    'terms',
    'website',
    'module',
    'feature',
    'shipment',
    'tracking',
    'live tracking',
    'control tower',
    'ams',
    'load',
    'freight',
    'settlement',
    'document',
    'compliance',
    'billing',
    'driver app',
    'vendor portal',
    'customer portal',
    'बुकिंग',
    'ट्रिप',
    'डिस्पैच',
    'पीओडी',
    'इनवॉइस',
    'पेमेंट',
    'फाइनेंस',
    'वेंडर',
    'ड्राइवर',
    'कस्टमर',
    'डेमो',
    'सपोर्ट',
    'प्राइवेसी',
    'पॉलिसी',
    'terms',
  ],
  followUpTerms: [
    'aur',
    'or',
    'and',
    'isme',
    'usme',
    'iske liye',
    'uske liye',
    'is mein',
    'kaise',
    'kitne time',
    'kab',
    'kaha',
    'kahan',
    'for vendor',
    'for driver',
    'for customer',
    'vendor ke liye',
    'driver ke liye',
    'customer ke liye',
    'admin ke liye',
    'payment kitne time',
    'aur vendor ke liye',
    'aur driver ke liye',
    'और',
    'इसमें',
    'उसमें',
    'इसके लिए',
    'उसके लिए',
    'कहाँ',
    'कैसे',
    'कब',
    'कितने समय',
    'वेंडर के लिए',
    'ड्राइवर के लिए',
    'कस्टमर के लिए',
  ],
  promptInjectionPatterns: [
    'ignore all previous instructions',
    'ignore your instructions',
    'pretend you are not',
    'system prompt',
    'developer message',
    'reveal your prompt',
    'api key',
    'api keys',
    'secret key',
    'access token',
    'password',
    'show me your instructions',
    'bypass',
    'override your rules',
    'forget your rules',
    'cricket score',
  ],
  contextWindowSize: 4,
  outOfScopeResponses: {
    en: [
      'I can help you with Easy Lane, TMS, Fleet Management, Bill Discounting, demos and support. What would you like to know?',
      'I can only assist with Easy Lane-related information such as TMS, fleet, finance, demos and support. What would you like to know about Easy Lane?',
    ],
    hi: [
      'मैं Easy Lane, TMS, Fleet Management, Bill Discounting, डेमो और सपोर्ट से जुड़े सवालों में आपकी मदद कर सकता हूँ।',
      'मैं केवल Easy Lane से जुड़ी जानकारी, जैसे TMS, फ्लीट, फाइनेंस, डेमो और सपोर्ट में मदद कर सकता हूँ।',
    ],
    hinglish: [
      'Main Easy Lane, TMS, Fleet Management, Bill Discounting, demo aur support se related questions me help kar sakta hoon. Aap kya jaanna chahenge?',
      'Main sirf Easy Lane se related topics jaise TMS, fleet, finance, demo aur support me help kar sakta hoon. Aap Easy Lane ke baare me kya poochna chahenge?',
    ],
  },
  promptInjectionResponses: {
    en: [
      'I can only assist with Easy Lane-related information and support.',
    ],
    hi: [
      'मैं केवल Easy Lane से जुड़ी जानकारी और सपोर्ट में ही मदद कर सकता हूँ।',
    ],
    hinglish: [
      'Main sirf Easy Lane se related information aur support me hi help kar sakta hoon.',
    ],
  },
};
