export const EASY_AI_KNOWLEDGE = [
  {
    id: 'easy-lane-overview',
    category: 'General',
    primaryQuestion: 'What is Easy Lane?',
    alternativeQuestions: ['Tell me about Easy Lane', 'What does Easy Lane do?', 'Explain Easy Lane', 'Easy Lane kya hai?', 'Easy Lane kya karta hai?', 'ईज़ी लेन क्या है?', 'ईज़ी लेन क्या करता है?'],
    keywords: ['easy lane', 'platform', 'logistics platform', 'overview', 'ईज़ी लेन', 'इजी लेन', 'kya hai', 'kya karta hai'],
    answer: 'Easy Lane is an AI-enabled logistics platform that brings transportation, fleet operations, live visibility and finance workflows into one connected system. It helps teams reduce manual work, respond faster and manage logistics with clearer operational control.',
    answers: {
      en: 'Easy Lane is an AI-enabled logistics platform that brings transportation, fleet operations, live visibility and finance workflows into one connected system. It helps teams reduce manual work, respond faster and manage logistics with clearer operational control. On the website, the platform is positioned as one place to manage shipments, vehicles, drivers, invoices, tracking and operational decisions more smoothly.',
      hi: 'Easy Lane एक AI-enabled logistics platform है जो transportation, fleet operations, live visibility और finance workflows को एक connected system में लाता है। इससे teams manual work कम कर सकती हैं, तेज़ response दे सकती हैं और operations को बेहतर control के साथ manage कर सकती हैं। वेबसाइट पर भी इसे एक ऐसे platform के रूप में दिखाया गया है जहाँ shipments, vehicles, drivers, invoices, tracking और operational decisions एक ही जगह से संभाले जा सकते हैं।',
      hinglish: 'Easy Lane ek AI-enabled logistics platform hai jo transportation, fleet operations, live visibility aur finance workflows ko ek connected system me laata hai. Isse teams manual work kam kar sakti hain, faster response de sakti hain aur operations ko better control ke saath manage kar sakti hain. Website ke hisaab se bhi Easy Lane ka focus yehi hai ki shipments, vehicles, drivers, invoices, tracking aur operational decisions ek hi platform se handle ho sakein.',
    },
    ctaLabel: 'Explore Easy Lane',
    ctaTarget: '#solutions',
    priority: 90,
    isEnabled: true,
  },
  {
    id: 'tms',
    category: 'TMS',
    primaryQuestion: 'Explain TMS',
    alternativeQuestions: ['What is TMS?', 'How does transport management work?', 'Tell me about transportation management', 'Easy Lane TMS kya karta hai?', 'TMS kya hai?', 'ईज़ी लेन का टीएमएस क्या करता है?', 'टीएमएस क्या है?'],
    keywords: ['tms', 'transport', 'transportation management', 'dispatch', 'trip management', 'टीएमएस', 'trip', 'booking'],
    answer: 'Easy Lane TMS helps plan, assign and monitor transportation operations from one place. Teams can manage trips, dispatching, vendors, costs, documents and delivery progress with real-time operational visibility.',
    answers: {
      en: 'Easy Lane TMS helps teams plan, assign and monitor transportation operations from one place. It brings order booking, load planning, freight execution and delivery progress into a single workflow with real-time visibility. The goal is to reduce manual coordination and keep dispatch, vendors and execution aligned.',
      hi: 'Easy Lane TMS teams को transportation operations एक ही जगह से plan, assign और monitor करने में मदद करता है। यह order booking, load planning, freight execution और delivery progress को real-time visibility के साथ एक single workflow में लाता है। इसका उद्देश्य manual coordination कम करना और dispatch, vendors तथा execution को aligned रखना है।',
      hinglish: 'Easy Lane TMS teams ko transportation operations ek hi jagah se plan, assign aur monitor karne me help karta hai. Ye order booking, load planning, freight execution aur delivery progress ko real-time visibility ke saath single workflow me laata hai. Iska main benefit ye hai ki manual coordination kam hota hai aur dispatch, vendors aur execution better aligned rehte hain.',
    },
    ctaLabel: 'Explore TMS',
    ctaTarget: '#solutions',
    priority: 100,
    isEnabled: true,
  },
  {
    id: 'fleet-management',
    category: 'Fleet',
    primaryQuestion: 'Explain Fleet Management',
    alternativeQuestions: ['What is fleet management?', 'How can I manage my fleet?', 'Tell me about the fleet module', 'Fleet kaise manage hota hai?', 'Fleet management kya hai?', 'फ्लीट कैसे manage होता है?', 'फ्लीट मैनेजमेंट क्या है?'],
    keywords: ['fleet', 'vehicles', 'maintenance', 'fuel', 'drivers', 'compliance', 'फ्लीट', 'vehicle', 'driver'],
    answer: 'Fleet Management centralizes vehicles, drivers, maintenance, fuel and compliance records. It gives operations teams a clearer view of fleet health, upcoming service needs and the information required to keep vehicles productive.',
    answers: {
      en: 'Fleet Management centralizes vehicles, drivers, maintenance, fuel and compliance records. It gives operations teams a clearer view of fleet health, upcoming service needs and the information required to keep vehicles productive. On the platform side, the focus is on keeping fleet records, movement visibility and driver coordination in one operational system.',
      hi: 'Fleet Management vehicles, drivers, maintenance, fuel और compliance records को एक जगह centralize करता है। इससे operations teams को fleet health, upcoming service needs और vehicles को productive रखने के लिए जरूरी जानकारी साफ़ रूप से मिलती है। Platform level पर इसका focus fleet records, movement visibility और driver coordination को एक operational system में रखना है।',
      hinglish: 'Fleet Management vehicles, drivers, maintenance, fuel aur compliance records ko ek jagah centralize karta hai. Isse operations teams ko fleet health, upcoming service needs aur vehicles ko productive rakhne ke liye zaroori information clear milti hai. Practical terms me, Easy Lane fleet records, movement visibility aur driver coordination ko ek operational system me laane ki koshish karta hai.',
    },
    ctaLabel: 'Explore Fleet',
    ctaTarget: '#solutions',
    priority: 95,
    isEnabled: true,
  },
  {
    id: 'ams',
    category: 'AMS',
    primaryQuestion: 'Explain AMS',
    alternativeQuestions: ['What is AMS?', 'Tell me about AMS', 'How does AMS work?', 'AMS kya hai?', 'एएमएस क्या है?'],
    keywords: ['ams', 'asset management', 'assets', 'एएमएस', 'asset'],
    answer: 'Easy Lane AMS supports structured asset visibility and lifecycle management. It helps teams organize asset records, monitor status and maintenance needs, and keep operational information accessible in one place.',
    answers: {
      en: 'Easy Lane AMS supports structured asset visibility and lifecycle management. It helps teams organize asset records, monitor status and maintenance needs, and keep operational information accessible in one place.',
      hi: 'Easy Lane AMS structured asset visibility और lifecycle management को support करता है। इससे teams asset records organize कर सकती हैं, status और maintenance needs monitor कर सकती हैं और operational information को एक जगह accessible रख सकती हैं।',
      hinglish: 'Easy Lane AMS structured asset visibility aur lifecycle management ko support karta hai. Isse teams asset records organize kar sakti hain, status aur maintenance needs monitor kar sakti hain aur operational information ko ek jagah accessible rakh sakti hain.',
    },
    ctaLabel: 'Explore AMS',
    ctaTarget: '#solutions',
    priority: 85,
    isEnabled: true,
  },
  {
    id: 'finance',
    category: 'Finance',
    primaryQuestion: 'Explain Finance Module',
    alternativeQuestions: ['What is the finance module?', 'How does bill discounting work?', 'Tell me about logistics finance', 'Bill discounting kya hai?', 'Vendor ko payment kaise milega?', 'Invoice kaha dikhega?', 'बिल डिस्काउंटिंग क्या है?', 'वेंडर को पेमेंट कैसे मिलेगा?', 'इनवॉइस कहाँ दिखेगा?'],
    keywords: ['finance', 'invoice', 'bill discounting', 'cash flow', 'payment', 'funding', 'पेमेंट', 'इनवॉइस', 'बिल डिस्काउंटिंग', 'vendor payment'],
    answer: 'The Finance Module improves invoice and payment visibility and supports bill discounting. Approved invoices can be converted into working capital, helping logistics businesses strengthen cash flow while keeping the process clear and traceable.',
    answers: {
      en: 'The Finance Module improves invoice and payment visibility and supports bill discounting. Approved invoices can be converted into working capital, helping logistics businesses strengthen cash flow while keeping the process clear and traceable. The broader platform messaging also includes auto invoicing, payment tracking, reconciliation and finance visibility tied back to logistics records.',
      hi: 'Finance Module invoice और payment visibility को बेहतर बनाता है और bill discounting को support करता है। Approved invoices को working capital में बदला जा सकता है, जिससे logistics businesses cash flow को मजबूत कर सकते हैं और process को clear और traceable रख सकते हैं। Platform messaging के हिसाब से इसमें auto invoicing, payment tracking, reconciliation और logistics records से जुड़ी finance visibility भी शामिल है।',
      hinglish: 'Finance Module invoice aur payment visibility ko improve karta hai aur bill discounting ko support karta hai. Approved invoices ko working capital me convert kiya ja sakta hai, jisse logistics businesses cash flow ko stronger bana sakte hain aur process clear aur traceable rehta hai. Broader Easy Lane platform context me isme auto invoicing, payment tracking, reconciliation aur logistics records se linked finance visibility bhi aati hai.',
    },
    ctaLabel: 'Explore Finance',
    ctaTarget: '#services',
    priority: 80,
    isEnabled: true,
  },
  {
    id: 'industries',
    category: 'Industries',
    primaryQuestion: 'What industries do you serve?',
    alternativeQuestions: ['Which industries use Easy Lane?', 'Who is Easy Lane for?', 'What sectors do you support?', 'Easy Lane kin industries ke liye hai?', 'Easy Lane किन industries के लिए है?'],
    keywords: ['industries', 'industry', 'fmcg', 'retail', 'manufacturing', 'pharma', 'cold chain', '3pl', 'industry', '3pl', 'enterprise'],
    answer: 'Easy Lane supports FMCG, retail, manufacturing, pharmaceutical, cold-chain, 3PL and aggregator operations. The platform is designed to adapt to businesses coordinating fleets, shipments, partners and logistics finance.',
    answers: {
      en: 'Easy Lane supports FMCG, retail, manufacturing, pharmaceutical, cold-chain, 3PL and aggregator operations. The platform is designed to adapt to businesses coordinating fleets, shipments, partners and logistics finance.',
      hi: 'Easy Lane FMCG, retail, manufacturing, pharmaceutical, cold-chain, 3PL और aggregator operations को support करता है। Platform उन businesses के लिए बनाया गया है जो fleets, shipments, partners और logistics finance को coordinate करते हैं।',
      hinglish: 'Easy Lane FMCG, retail, manufacturing, pharmaceutical, cold-chain, 3PL aur aggregator operations ko support karta hai. Platform un businesses ke liye design kiya gaya hai jo fleets, shipments, partners aur logistics finance ko coordinate karte hain.',
    },
    ctaLabel: 'View Solutions',
    ctaTarget: '#solutions',
    priority: 75,
    isEnabled: true,
  },
  {
    id: 'live-tracking',
    category: 'Tracking',
    primaryQuestion: 'How does live tracking work?',
    alternativeQuestions: ['Explain live tracking', 'Can I track vehicles?', 'How do I track a shipment?', 'Can vehicles be tracked in real time?', 'Mere trucks live track ho sakte hain?', 'Live tracking kaise kaam karta hai?', 'लाइव ट्रैकिंग कैसे काम करती है?'],
    keywords: ['tracking', 'live tracking', 'gps', 'vehicle location', 'shipment', 'eta', 'visibility', 'truck location', 'real time tracking', 'ट्रैकिंग', 'लाइव ट्रैकिंग'],
    answer: 'Live tracking brings vehicle locations, route progress, ETAs and delivery updates into the Control Tower. Operations teams can monitor active movement, identify exceptions and respond without switching between disconnected tools.',
    answers: {
      en: 'Live tracking brings vehicle locations, route progress, ETAs and delivery updates into the Control Tower. Operations teams can monitor active movement, identify exceptions and respond without switching between disconnected tools. The website also positions this as part of broader visibility, alerts and exception awareness across active logistics execution.',
      hi: 'Live tracking vehicle locations, route progress, ETA और delivery updates को Control Tower में लाता है। Operations teams active movement monitor कर सकती हैं, exceptions पहचान सकती हैं और अलग-अलग tools में जाए बिना response दे सकती हैं। वेबसाइट पर भी इसे broader visibility, alerts और exception awareness के हिस्से के रूप में दिखाया गया है।',
      hinglish: 'Live tracking vehicle locations, route progress, ETA aur delivery updates ko Control Tower me laata hai. Operations teams active movement monitor kar sakti hain, exceptions identify kar sakti hain aur alag tools me switch kiye bina response de sakti hain. Website context me ye visibility, alerts aur exception awareness ka important part hai.',
    },
    ctaLabel: 'Explore Control Tower',
    ctaTarget: '#contact',
    priority: 100,
    isEnabled: true,
  },
  {
    id: 'integrations',
    category: 'Integrations',
    primaryQuestion: 'What integrations are supported?',
    alternativeQuestions: ['Can Easy Lane integrate with my systems?', 'Tell me about integrations', 'Do you support API integrations?', 'Integrations kaun si supported hain?', 'क्या integrations supported हैं?'],
    keywords: ['integration', 'integrations', 'api', 'erp', 'system', 'connect', 'इंटीग्रेशन', 'api integration'],
    answer: 'Easy Lane can be aligned with the systems involved in your logistics workflows. Integration scope depends on your operational setup, so the team can review your ERP, tracking, finance and partner-system requirements during a solution discussion.',
    answers: {
      en: 'Easy Lane can be aligned with the systems involved in your logistics workflows. Integration scope depends on your operational setup, so the team can review your ERP, tracking, finance and partner-system requirements during a solution discussion.',
      hi: 'Easy Lane को आपके logistics workflows में शामिल systems के साथ align किया जा सकता है। Integration scope आपके operational setup पर depend करता है, इसलिए team ERP, tracking, finance और partner-system requirements को solution discussion के दौरान review कर सकती है।',
      hinglish: 'Easy Lane ko aapke logistics workflows me involved systems ke saath align kiya ja sakta hai. Integration scope aapke operational setup par depend karta hai, isliye team ERP, tracking, finance aur partner-system requirements ko solution discussion ke dauran review kar sakti hai.',
    },
    ctaLabel: 'Contact Sales',
    ctaTarget: '#contact',
    priority: 70,
    isEnabled: true,
  },
  {
    id: 'book-demo',
    category: 'Demo',
    primaryQuestion: 'Can I book a demo?',
    alternativeQuestions: ['Book a demo', 'I want a demo', 'How can I see the platform?', 'Talk to sales', 'Mujhe demo book karna hai', 'Demo kaise book karu?', 'मुझे डेमो बुक करना है', 'डेमो कैसे बुक करूँ?'],
    keywords: ['demo', 'book', 'sales', 'contact', 'meeting', 'डेमो', 'बुक', 'demo book'],
    answer: 'Yes. You can request a tailored Easy Lane walkthrough based on your logistics operations, priorities and the modules you want to explore.',
    answers: {
      en: 'Yes. You can request a tailored Easy Lane walkthrough based on your logistics operations, priorities and the modules you want to explore. The current website demo form asks for details such as name, work email, phone number, company, company size and the module you are interested in.',
      hi: 'हाँ। आप अपने logistics operations, priorities और जिन modules को देखना चाहते हैं उनके आधार पर tailored Easy Lane walkthrough request कर सकते हैं। वर्तमान वेबसाइट demo form में नाम, work email, phone number, company, company size और interested module जैसी details ली जाती हैं।',
      hinglish: 'Haan. Aap apne logistics operations, priorities aur jin modules ko explore karna chahte hain unke basis par tailored Easy Lane walkthrough request kar sakte hain. Current website demo form me name, work email, phone number, company, company size aur interested module jaise details maange jaate hain.',
    },
    ctaLabel: 'Book Demo',
    ctaTarget: '#contact',
    priority: 60,
    isEnabled: true,
  },
  {
    id: 'support',
    category: 'Support',
    primaryQuestion: 'How can I contact support?',
    alternativeQuestions: ['I need support', 'Contact support', 'Mujhe support chahiye', 'Support kaise milega?', 'मुझे सपोर्ट चाहिए', 'सपोर्ट कैसे मिलेगा?'],
    keywords: ['support', 'help', 'contact support', 'assistance', 'सपोर्ट', 'help'],
    answer: 'You can contact the Easy Lane team through the website contact section to get support or discuss your operational needs.',
    answers: {
      en: 'You can contact the Easy Lane team through the website contact section to get support or discuss your operational needs. The current contact information on the website includes phone, email, office location and a dedicated support contact.',
      hi: 'आप support पाने या अपनी operational needs पर बात करने के लिए वेबसाइट के contact section के माध्यम से Easy Lane team से संपर्क कर सकते हैं। वेबसाइट पर अभी phone, email, office location और dedicated support contact की जानकारी दी गई है।',
      hinglish: 'Aap support lene ya apni operational needs discuss karne ke liye website ke contact section ke through Easy Lane team se contact kar sakte hain. Current website par phone, email, office location aur dedicated support contact ki details available hain.',
    },
    ctaLabel: 'Contact Support',
    ctaTarget: '#contact',
    priority: 65,
    isEnabled: true,
  },
  {
    id: 'privacy-policy',
    category: 'Policy',
    primaryQuestion: 'Where can I find the Privacy Policy?',
    alternativeQuestions: ['Show me Easy Lane privacy policy', 'What are the terms?', 'Privacy policy kaha hai?', 'प्राइवेसी पॉलिसी कहाँ है?', 'Terms kya hain?'],
    keywords: ['privacy policy', 'privacy', 'terms', 'policy', 'प्राइवेसी', 'पॉलिसी'],
    answer: 'You can review Easy Lane privacy and policy-related information on the website policy pages.',
    answers: {
      en: 'You can review Easy Lane privacy and policy-related information on the website policy pages. The current privacy page explains what information is collected, how it is used, sharing and disclosure boundaries, retention, security and how users can contact Easy Lane for privacy-related questions.',
      hi: 'आप Easy Lane की privacy और policy से जुड़ी जानकारी वेबसाइट के policy pages पर देख सकते हैं। वर्तमान privacy page में information collection, use, sharing and disclosure, retention, security और privacy-related queries के लिए contact options के बारे में जानकारी दी गई है।',
      hinglish: 'Aap Easy Lane ki privacy aur policy se related information website ke policy pages par dekh sakte hain. Current privacy page me information collection, use, sharing and disclosure, retention, security aur privacy-related queries ke liye contact options explain kiye gaye hain.',
    },
    ctaLabel: 'View Policy',
    ctaTarget: '#contact',
    priority: 50,
    isEnabled: true,
  },
  {
    id: 'vendor-portal',
    category: 'Vendor',
    primaryQuestion: 'How does the vendor portal work?',
    alternativeQuestions: ['Vendor portal kya karta hai?', 'Vendor ko kya features milte hain?', 'Vendor dashboard me kya hota hai?', 'Vendor ko payment kaise milega?', 'Vendor invoice kaha upload karega?', 'वेंडर पोर्टल कैसे काम करता है?', 'वेंडर को पेमेंट कैसे मिलेगा?'],
    keywords: ['vendor', 'vendor portal', 'vendor dashboard', 'invoice upload', 'pod upload', 'settlement history', 'payment notifications', 'bill discounting access', 'वेंडर', 'वेंडर पोर्टल'],
    answer: 'The vendor portal gives transport vendors one place to manage assigned loads, upload invoices and POD, monitor payments, access bill discounting, track settlements and keep compliance documents organized.',
    answers: {
      en: 'The vendor portal gives transport vendors one place to manage assigned loads, upload invoices and POD, monitor payments, access bill discounting, track settlements and keep compliance documents organized. The current website vendor dashboard also highlights trip assignment, invoice upload, POD upload, settlement history, payment notifications and vendor performance visibility.',
      hi: 'Vendor portal transport vendors को एक ऐसी centralized जगह देता है जहाँ वे assigned loads manage कर सकते हैं, invoices और POD upload कर सकते हैं, payments monitor कर सकते हैं, bill discounting access देख सकते हैं, settlements track कर सकते हैं और compliance documents organized रख सकते हैं। वर्तमान वेबसाइट vendor dashboard में trip assignment, invoice upload, POD upload, settlement history, payment notifications और vendor performance visibility भी highlight की गई है।',
      hinglish: 'Vendor portal transport vendors ko ek centralized workspace deta hai jahan wo assigned loads manage kar sakte hain, invoice aur POD upload kar sakte hain, payments monitor kar sakte hain, bill discounting access dekh sakte hain, settlements track kar sakte hain aur compliance documents organized rakh sakte hain. Current website vendor dashboard me trip assignment, invoice upload, POD upload, settlement history, payment notifications aur vendor performance visibility bhi clearly dikhayi gayi hai.',
    },
    ctaLabel: 'Contact Support',
    ctaTarget: '#contact',
    priority: 98,
    isEnabled: true,
  },
  {
    id: 'driver-workflows',
    category: 'Driver',
    primaryQuestion: 'How do driver workflows work?',
    alternativeQuestions: ['Driver workflow kya hai?', 'Driver trip ka POD kaha upload karega?', 'Driver ke liye Easy Lane kya karta hai?', 'Driver management kaise hota hai?', 'ड्राइवर ट्रिप का POD कहाँ upload करेगा?', 'ड्राइवर मैनेजमेंट कैसे होता है?'],
    keywords: ['driver', 'driver workflow', 'driver app', 'pod', 'trip assignment', 'route communication', 'driver management', 'proof of delivery', 'ड्राइवर', 'ड्राइवर ऐप'],
    answer: 'Easy Lane keeps driver coordination connected to the wider logistics workflow. The platform supports trip assignment, route communication, execution visibility and proof of delivery handling so driver-side updates stay connected with operations.',
    answers: {
      en: 'Easy Lane keeps driver coordination connected to the wider logistics workflow. The platform supports trip assignment, route communication, execution visibility and proof of delivery handling so driver-side updates stay connected with operations. The public website also describes the driver side as part of a broader workflow with better visibility and less manual follow-up.',
      hi: 'Easy Lane driver coordination को wider logistics workflow से connected रखता है। Platform trip assignment, route communication, execution visibility और proof of delivery handling को support करता है ताकि driver-side updates operations के साथ जुड़े रहें। सार्वजनिक वेबसाइट भी driver side को better visibility और कम manual follow-up वाले broader workflow के हिस्से के रूप में दिखाती है।',
      hinglish: 'Easy Lane driver coordination ko wider logistics workflow se connected rakhta hai. Platform trip assignment, route communication, execution visibility aur proof of delivery handling ko support karta hai taki driver-side updates operations ke saath linked rahein. Public website ke hisaab se bhi driver side ka focus better visibility aur kam manual follow-up par hai.',
    },
    ctaLabel: 'Explore Fleet',
    ctaTarget: '#solutions',
    priority: 94,
    isEnabled: true,
  },
  {
    id: 'invoice-pod',
    category: 'Finance',
    primaryQuestion: 'How are invoice and POD handled?',
    alternativeQuestions: ['Invoice kaha upload hoga?', 'POD kaha upload hoga?', 'Customer invoice kaha dekh sakta hai?', 'Invoices kaise manage hote hain?', 'POD upload kaise hoga?', 'इनवॉइस कहाँ upload होगा?', 'POD कैसे upload होगा?'],
    keywords: ['invoice', 'pod', 'proof of delivery', 'invoice management', 'document handling', 'auto invoicing', 'इनवॉइस', 'पीओडी'],
    answer: 'Easy Lane keeps invoice and POD workflows connected to the trip record. The platform supports document handling, proof of delivery, invoice visibility and finance tracking so teams do not have to manage these records in disconnected places.',
    answers: {
      en: 'Easy Lane keeps invoice and POD workflows connected to the trip record. The platform supports document handling, proof of delivery, invoice visibility and finance tracking so teams do not have to manage these records in disconnected places. On the website side, invoice management, POD support and auto invoicing are positioned as part of the same operational flow.',
      hi: 'Easy Lane invoice और POD workflows को trip record से connected रखता है। Platform document handling, proof of delivery, invoice visibility और finance tracking को support करता है ताकि teams को ये records अलग-अलग जगह manage न करने पड़ें। वेबसाइट पर भी invoice management, POD support और auto invoicing को इसी operational flow का हिस्सा दिखाया गया है।',
      hinglish: 'Easy Lane invoice aur POD workflows ko trip record se connected rakhta hai. Platform document handling, proof of delivery, invoice visibility aur finance tracking ko support karta hai taki teams ko ye records alag-alag jagah manage na karne padhein. Website par bhi invoice management, POD support aur auto invoicing ko same operational flow ka part dikhaya gaya hai.',
    },
    ctaLabel: 'Explore Finance',
    ctaTarget: '#services',
    priority: 97,
    isEnabled: true,
  },
  {
    id: 'payments-settlements',
    category: 'Finance',
    primaryQuestion: 'How do payments and settlements work?',
    alternativeQuestions: ['Payment tracking kaise hoti hai?', 'Vendor ko payment ka status kaha dikhega?', 'Settlement history kaha milegi?', 'Payment visibility kaise hoti hai?', 'पेमेंट ट्रैकिंग कैसे होती है?', 'सेटलमेंट हिस्ट्री कहाँ मिलेगी?'],
    keywords: ['payment', 'payments', 'settlement', 'settlements', 'payment tracking', 'vendor payments', 'payment visibility', 'settlement history', 'पेमेंट', 'सेटलमेंट'],
    answer: 'Easy Lane keeps payment and settlement visibility tied to invoice and shipment records. That gives teams a cleaner view of payment status instead of relying on separate follow-ups and manual tracking.',
    answers: {
      en: 'Easy Lane keeps payment and settlement visibility tied to invoice and shipment records. That gives teams a cleaner view of payment status instead of relying on separate follow-ups and manual tracking. The website payment-related modules also describe this as a way to keep finance workflow visible and connected to the underlying logistics record.',
      hi: 'Easy Lane payment और settlement visibility को invoice और shipment records से जोड़े रखता है। इससे teams को payment status का clearer view मिलता है और अलग-अलग follow-ups या manual tracking पर निर्भरता कम होती है। वेबसाइट के payment-related modules भी इसे finance workflow को underlying logistics record से connected रखने के तरीके के रूप में बताते हैं।',
      hinglish: 'Easy Lane payment aur settlement visibility ko invoice aur shipment records se linked rakhta hai. Isse teams ko payment status ka cleaner view milta hai aur alag follow-ups ya manual tracking par dependency kam hoti hai. Website ke payment-related modules bhi isi baat par focus karte hain ki finance workflow logistics record se connected rahe.',
    },
    ctaLabel: 'Contact Support',
    ctaTarget: '#contact',
    priority: 96,
    isEnabled: true,
  },
  {
    id: 'customer-workflows',
    category: 'Customer',
    primaryQuestion: 'How do customer workflows work?',
    alternativeQuestions: ['Customer ko kya visibility milti hai?', 'Customer invoice kaha dekh sakta hai?', 'Customer workflow kya hota hai?', 'Customer side par kya dikhega?', 'कस्टमर को क्या visibility मिलती है?', 'कस्टमर invoice कहाँ देख सकता है?'],
    keywords: ['customer', 'customer workflow', 'customer visibility', 'invoice visibility', 'tracking visibility', 'shipment visibility', 'कस्टमर'],
    answer: 'Easy Lane is designed to give business users clearer shipment, tracking and finance visibility through one connected platform. Customer-side workflows are generally aligned around visibility, operational control and easier access to the right records.',
    answers: {
      en: 'Easy Lane is designed to give business users clearer shipment, tracking and finance visibility through one connected platform. Customer-side workflows are generally aligned around visibility, operational control and easier access to the right records, rather than fragmented manual coordination.',
      hi: 'Easy Lane business users को shipment, tracking और finance visibility एक connected platform के माध्यम से बेहतर तरीके से देने के लिए designed है। Customer-side workflows आम तौर पर visibility, operational control और सही records तक आसान access पर केंद्रित रहते हैं, न कि fragmented manual coordination पर।',
      hinglish: 'Easy Lane business users ko shipment, tracking aur finance visibility ek connected platform ke through better tareeke se dene ke liye design kiya gaya hai. Customer-side workflows ka focus generally visibility, operational control aur right records tak easy access par hota hai, na ki fragmented manual coordination par.',
    },
    ctaLabel: 'Explore Easy Lane',
    ctaTarget: '#solutions',
    priority: 82,
    isEnabled: true,
  },
  {
    id: 'admin-operations',
    category: 'Admin',
    primaryQuestion: 'What does the admin side cover?',
    alternativeQuestions: ['Admin workflow kya hota hai?', 'Admin ko kya control milta hai?', 'Admin side par kya manage hota hai?', 'एडमिन workflow क्या होता है?'],
    keywords: ['admin', 'admin workflow', 'operations dashboard', 'control', 'visibility', 'management', 'एडमिन'],
    answer: 'The admin and operations side of Easy Lane is centered on visibility, coordination and control across trips, vendors, drivers, invoices and support activity.',
    answers: {
      en: 'The admin and operations side of Easy Lane is centered on visibility, coordination and control across trips, vendors, drivers, invoices and support activity. The current site positioning emphasizes one platform for logistics execution, finance visibility and operational decision-making rather than separate disconnected tools.',
      hi: 'Easy Lane का admin और operations side trips, vendors, drivers, invoices और support activity के across visibility, coordination और control पर केंद्रित है। वर्तमान साइट positioning भी यही बताती है कि logistics execution, finance visibility और operational decision-making के लिए एक unified platform हो, अलग-अलग disconnected tools नहीं।',
      hinglish: 'Easy Lane ka admin aur operations side trips, vendors, drivers, invoices aur support activity ke across visibility, coordination aur control par focus karta hai. Current site positioning bhi isi direction me hai ki logistics execution, finance visibility aur operational decision-making ke liye ek unified platform mile, alag-alag disconnected tools nahi.',
    },
    ctaLabel: 'Explore Easy Lane',
    ctaTarget: '#solutions',
    priority: 78,
    isEnabled: true,
  },
  {
    id: 'website-overview',
    category: 'General',
    primaryQuestion: 'What does the Easy Lane website cover?',
    alternativeQuestions: ['Website me kya-kya hai?', 'Easy Lane website par kya information milegi?', 'Website kis baare me batati hai?', 'ईज़ी लेन वेबसाइट में क्या है?'],
    keywords: ['website', 'easy lane website', 'modules', 'features', 'contact', 'book demo', 'privacy policy', 'platform pages', 'वेबसाइट'],
    answer: 'The Easy Lane website explains the platform, its modules, logistics workflows, finance features, contact options, demo request flow and policy pages.',
    answers: {
      en: 'The Easy Lane website explains the platform, its modules, logistics workflows, finance features, contact options, demo request flow and policy pages. It currently includes platform/module pages such as TMS, fleet, bill discounting, tracking and related business information.',
      hi: 'Easy Lane वेबसाइट platform, उसके modules, logistics workflows, finance features, contact options, demo request flow और policy pages के बारे में बताती है। इसमें अभी TMS, fleet, bill discounting, tracking और related business information वाले pages शामिल हैं।',
      hinglish: 'Easy Lane website platform, uske modules, logistics workflows, finance features, contact options, demo request flow aur policy pages ke baare me batati hai. Isme abhi TMS, fleet, bill discounting, tracking aur related business information wale pages included hain.',
    },
    ctaLabel: 'Explore Easy Lane',
    ctaTarget: '#solutions',
    priority: 72,
    isEnabled: true,
  },
];

export const EASY_AI_SUGGESTIONS = [
  'What is Easy Lane?',
  'Explain TMS',
  'Explain Fleet Management',
  'Explain AMS',
  'Explain Finance Module',
  'What industries do you serve?',
  'How does live tracking work?',
  'Can I book a demo?',
];

export const EASY_AI_FALLBACK = `I don't have a verified answer for that yet.

You can ask about:

• TMS
• Fleet
• AMS
• Finance
• Tracking
• Integrations
• Book Demo`;
