import crypto from 'node:crypto';
import cors from 'cors';
import express from 'express';
import mongoose from 'mongoose';
import { config, missingAdminEnvironment } from './config.js';
import { cookieOptions, createAdminToken, requireAdmin } from './auth.js';
import { Lead } from './models/Lead.js';
import { defaultContent, SiteContent } from './models/SiteContent.js';
import { aiKnowledgeAdminRouter, aiKnowledgePublicRouter } from './routes/aiKnowledgeRoutes.js';
import { assistantAdminRouter, assistantPublicRouter } from './routes/assistantRoutes.js';
import { contactLeadAdminRouter, contactLeadPublicRouter } from './routes/contactLeadRoutes.js';

const statuses = ['new', 'contacted', 'qualified', 'scheduled', 'won', 'lost'];
const trustedLogoSpeeds = ['slow', 'normal', 'fast'];
const safeLead = (lead) => lead.toObject();
const csv = (value) => `"${String(value ?? '').replaceAll('"', '""')}"`;
const validLinkUrl = (value) => { const url = String(value || '').trim(); if (url.startsWith('/') && !url.startsWith('//')) return url; try { const parsed = new URL(url); return ['http:', 'https:'].includes(parsed.protocol) ? url : ''; } catch { return ''; } };
const cleanNavigationLink = (body = {}) => { const label = String(body.label || '').trim(); const url = validLinkUrl(body.url); const location = body.location === 'footer' ? 'footer' : body.location === 'header' ? 'header' : ''; if (!label) return { error: 'Label is required.' }; if (!url) return { error: 'URL must be an internal route or a valid http/https URL.' }; if (!location) return { error: 'Location must be Header or Footer.' }; return { value: { label, url, location, group: String(body.group || '').trim(), order: Number.isFinite(Number(body.order)) ? Number(body.order) : 0, enabled: body.enabled !== false, newTab: body.newTab === true } }; };
const normaliseTrustedLogos = (value = {}) => ({
  enabled: typeof value.enabled === 'boolean' ? value.enabled : true,
  animationEnabled: typeof value.animationEnabled === 'boolean' ? value.animationEnabled : true,
  animationSpeed: trustedLogoSpeeds.includes(value.animationSpeed) ? value.animationSpeed : 'normal'
});

export const app = express();
app.disable('x-powered-by');
app.use(cors({ origin: config().clientUrl, credentials: true, methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS'] }));
app.use(express.json({ limit: '2mb' }));
export const adminRouter = express.Router();
export const adminSettingsRouter = express.Router();
app.use('/api/admin/settings', adminSettingsRouter);
app.use('/api/admin', adminRouter);
app.use('/api', aiKnowledgePublicRouter);
app.use('/api/assistant', assistantPublicRouter);
app.use('/api', contactLeadPublicRouter);

app.get('/api/health', (_, res) => res.json({ success: true, message: 'Easy Lane API is running' }));
function handleAdminLogin(req, res) {
  const missing = missingAdminEnvironment();
  if (missing.length) return res.status(500).json({ success: false, message: 'Admin authentication is not configured on the server.' });
  const { adminId = '', password = '' } = req.body || {};
  const settings = config();
  const validId = String(adminId).trim().toLowerCase() === settings.adminId.toLowerCase();
  const passwordBuffer = Buffer.from(String(password));
  const configuredBuffer = Buffer.from(settings.adminPassword);
  const validPassword = passwordBuffer.length === configuredBuffer.length && crypto.timingSafeEqual(passwordBuffer, configuredBuffer);
  if (!validId || !validPassword) return res.status(401).json({ success: false, message: 'Invalid Admin ID or password.' });
  const token = createAdminToken();
  res.cookie(settings.cookieName, token, cookieOptions());
  return res.json({ success: true, token, admin: { id: settings.adminId } });
}

app.post('/api/admin/login', handleAdminLogin);
app.post('/api/admin/auth/login', handleAdminLogin);
app.get('/api/admin/auth/me', requireAdmin, (req, res) => res.json({ admin: req.admin }));
app.post('/api/admin/auth/logout', (_, res) => { const settings = config(); res.clearCookie(settings.cookieName, { httpOnly: true, sameSite: 'lax', secure: settings.nodeEnv === 'production', path: '/' }); res.json({ success: true }); });

app.use('/api/admin', aiKnowledgeAdminRouter);
app.use('/api/admin', assistantAdminRouter);
app.use('/api/admin', contactLeadAdminRouter);

app.get('/api/content', async (_, res, next) => { try { const content = await SiteContent.findOneAndUpdate({ key: 'homepage' }, { $setOnInsert: defaultContent }, { upsert: true, new: true, setDefaultsOnInsert: true }); res.json(content); } catch (error) { next(error); } });
app.patch('/api/admin/content', requireAdmin, async (req, res, next) => { try { const { hero, cta } = req.body || {}; const content = await SiteContent.findOneAndUpdate({ key: 'homepage' }, { $set: { hero, cta } }, { new: true, runValidators: true }); res.json(content); } catch (error) { next(error); } });
app.get('/api/settings/public', async (_, res, next) => { try { const settings = await SiteContent.findOneAndUpdate({ key: 'homepage' }, { $setOnInsert: defaultContent }, { upsert: true, new: true, setDefaultsOnInsert: true }); const socialLinks = settings.socialLinks || {}; const navigationLinks = (settings.navigationLinks || []).filter((link) => link.enabled).sort((a, b) => a.order - b.order).map(({ label, url, location, group, order, newTab }) => ({ label, url, location, group, order, newTab })); res.set('Cache-Control', 'no-store'); res.json({ socialLinks: { linkedin: socialLinks.linkedin || '', facebook: socialLinks.facebook || '', youtube: socialLinks.youtube || '', twitter: socialLinks.twitter || '' }, navigationLinks, trustedLogos: normaliseTrustedLogos(settings.trustedLogos) }); } catch (error) { next(error); } });
app.get('/api/admin/settings', requireAdmin, async (_, res, next) => { try { const settings = await SiteContent.findOneAndUpdate({ key: 'homepage' }, { $setOnInsert: defaultContent }, { upsert: true, new: true, setDefaultsOnInsert: true }); const socialLinks = settings.socialLinks || {}; res.set('Cache-Control', 'no-store'); res.json({ socialLinks: { linkedin: socialLinks.linkedin || '', facebook: socialLinks.facebook || '', youtube: socialLinks.youtube || '', twitter: socialLinks.twitter || '' }, trustedLogos: normaliseTrustedLogos(settings.trustedLogos) }); } catch (error) { next(error); } });
adminSettingsRouter.get('/trusted-logos', requireAdmin, async (req, res, next) => { try { console.log('[Trusted Logos Controller Hit]', { method: req.method, body: req.body, cookieAuthPresent: Boolean(req.cookies || req.headers.cookie) }); console.log('[Trusted Logos Database Query]', { operation: 'findOneAndUpdate', key: 'homepage' }); const settings = await SiteContent.findOneAndUpdate({ key: 'homepage' }, { $setOnInsert: defaultContent }, { upsert: true, new: true, setDefaultsOnInsert: true }); res.set('Cache-Control', 'no-store'); console.log('[Trusted Logos Response Sent]', { method: req.method, status: 200 }); res.json({ success: true, trustedLogos: normaliseTrustedLogos(settings.trustedLogos) }); } catch (error) { next(error); } });
adminSettingsRouter.put('/trusted-logos', requireAdmin, async (req, res, next) => { try { console.log('[Trusted Logos Controller Hit]', { method: req.method, body: req.body, cookieAuthPresent: Boolean(req.cookies || req.headers.cookie) }); const { enabled, animationEnabled, animationSpeed } = req.body || {}; if (typeof enabled !== 'boolean' || typeof animationEnabled !== 'boolean') return res.status(400).json({ message: 'Section and animation settings must be true or false.' }); if (!trustedLogoSpeeds.includes(animationSpeed)) return res.status(400).json({ message: 'Animation speed must be slow, normal, or fast.' }); console.log('[Trusted Logos Database Query]', { operation: 'findOneAndUpdate', key: 'homepage' }); const settings = await SiteContent.findOneAndUpdate({ key: 'homepage' }, { $set: { 'trustedLogos.enabled': enabled, 'trustedLogos.animationEnabled': animationEnabled, 'trustedLogos.animationSpeed': animationSpeed }, $setOnInsert: { hero: defaultContent.hero, cta: defaultContent.cta, socialLinks: defaultContent.socialLinks, navigationLinks: defaultContent.navigationLinks } }, { upsert: true, new: true, runValidators: true, setDefaultsOnInsert: true }); console.log('[Trusted Logos Response Sent]', { method: req.method, status: 200 }); res.json({ success: true, trustedLogos: normaliseTrustedLogos(settings.trustedLogos) }); } catch (error) { next(error); } });
app.put('/api/admin/settings/social-links', requireAdmin, async (req, res, next) => { try { const keys = ['linkedin', 'facebook', 'youtube', 'twitter']; const socialLinks = {}; for (const key of keys) { const value = String(req.body?.[key] ?? '').trim(); if (value) { let parsed; try { parsed = new URL(value); } catch { return res.status(400).json({ message: `${key} must be a valid URL.` }); } if (!['http:', 'https:'].includes(parsed.protocol)) return res.status(400).json({ message: `${key} must use http:// or https://.` }); } socialLinks[key] = value; } const settings = await SiteContent.findOneAndUpdate({ key: 'homepage' }, { $set: { socialLinks }, $setOnInsert: { hero: defaultContent.hero, cta: defaultContent.cta } }, { upsert: true, new: true, runValidators: true, setDefaultsOnInsert: true }); res.json({ socialLinks: settings.socialLinks }); } catch (error) { next(error); } });
app.get('/api/admin/navigation-links', requireAdmin, async (_, res, next) => { try { const settings = await SiteContent.findOneAndUpdate({ key: 'homepage' }, { $setOnInsert: defaultContent }, { upsert: true, new: true, setDefaultsOnInsert: true }); res.json({ items: (settings.navigationLinks || []).sort((a, b) => a.order - b.order) }); } catch (error) { next(error); } });
app.post('/api/admin/navigation-links', requireAdmin, async (req, res, next) => { try { const cleaned = cleanNavigationLink(req.body); if (cleaned.error) return res.status(400).json({ message: cleaned.error }); const settings = await SiteContent.findOneAndUpdate({ key: 'homepage' }, { $push: { navigationLinks: cleaned.value }, $setOnInsert: { hero: defaultContent.hero, cta: defaultContent.cta, socialLinks: defaultContent.socialLinks } }, { upsert: true, new: true, runValidators: true, setDefaultsOnInsert: true }); res.status(201).json(settings.navigationLinks.at(-1)); } catch (error) { next(error); } });
app.patch('/api/admin/navigation-links/:id', requireAdmin, async (req, res, next) => { try { const cleaned = cleanNavigationLink(req.body); if (cleaned.error) return res.status(400).json({ message: cleaned.error }); const fields = Object.fromEntries(Object.entries(cleaned.value).map(([key, value]) => ['navigationLinks.$.' + key, value])); const settings = await SiteContent.findOneAndUpdate({ key: 'homepage', 'navigationLinks._id': req.params.id }, { $set: fields }, { new: true, runValidators: true }); if (!settings) return res.status(404).json({ message: 'Navigation link not found.' }); res.json(settings.navigationLinks.id(req.params.id)); } catch (error) { next(error); } });
app.delete('/api/admin/navigation-links/:id', requireAdmin, async (req, res, next) => { try { const settings = await SiteContent.findOneAndUpdate({ key: 'homepage', 'navigationLinks._id': req.params.id }, { $pull: { navigationLinks: { _id: req.params.id } } }, { new: true }); if (!settings) return res.status(404).json({ message: 'Navigation link not found.' }); res.json({ success: true }); } catch (error) { next(error); } });

app.post('/api/leads', async (req, res, next) => { try { const { name, email, phone, company, fleetSize, message } = req.body || {}; const lead = await Lead.create({ name, email, phone, company, fleetSize, message }); res.status(201).json({ bookingId: lead.bookingId, message: 'Demo request received.' }); } catch (error) { if (error?.code === 11000) return res.status(409).json({ message: 'A current demo request already exists for this email.' }); return next(error); } });

app.get('/api/admin/leads', requireAdmin, async (req, res, next) => { try { const page = Math.max(1, Number(req.query.page) || 1); const limit = Math.min(100, Math.max(1, Number(req.query.limit) || 10)); const query = { archived: req.query.archived === 'true' }; if (statuses.includes(req.query.status)) query.status = req.query.status; if (req.query.search) { const term = new RegExp(String(req.query.search).replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'i'); query.$or = [{ name: term }, { email: term }, { company: term }, { bookingId: term }]; } const [items, total] = await Promise.all([Lead.find(query).sort({ createdAt: -1 }).skip((page - 1) * limit).limit(limit), Lead.countDocuments(query)]); res.json({ items: items.map(safeLead), total, page, pages: Math.max(1, Math.ceil(total / limit)) }); } catch (error) { next(error); } });
adminRouter.post('/leads/bulk-delete', requireAdmin, async (req, res, next) => { try { console.log('[Bulk Delete Leads Controller Entered]', { count: Array.isArray(req.body?.ids) ? req.body.ids.length : 0 }); const requested = Array.isArray(req.body?.ids) ? [...new Set(req.body.ids.map(String))] : []; if (!requested.length) return res.status(400).json({ message: 'At least one lead ID is required.' }); if (requested.length > 100) return res.status(400).json({ message: 'A maximum of 100 leads may be deleted at once.' }); const invalid = requested.filter((id) => !mongoose.isValidObjectId(id)); if (invalid.length) return res.status(400).json({ message: 'One or more lead IDs are invalid.', failed: invalid }); console.log('[Bulk Delete Leads Database Query]', { operation: 'deleteMany', count: requested.length }); const existing = await Lead.find({ _id: { $in: requested } }).select('_id'); const found = new Set(existing.map((lead) => String(lead._id))); const notFound = requested.filter((id) => !found.has(id)); const deleted = await Lead.deleteMany({ _id: { $in: [...found] } }); console.log('[Bulk Delete Leads Response Sent]', { status: 200, deletedCount: deleted.deletedCount }); res.json({ deletedCount: deleted.deletedCount, notFound, failed: [] }); } catch (error) { next(error); } });
app.get('/api/admin/leads/:id', requireAdmin, async (req, res, next) => { try { const lead = await Lead.findById(req.params.id); if (!lead) return res.status(404).json({ message: 'Lead not found.' }); res.json(safeLead(lead)); } catch (error) { next(error); } });
adminRouter.delete('/leads/:id', requireAdmin, async (req, res) => { try { const id = String(req.params.id || '').trim(); console.log('[Delete Lead Controller Entered]', id); if (!mongoose.isValidObjectId(id)) return res.status(400).json({ success: false, message: 'Invalid lead ID' }); console.log('[Delete Lead Database Query]', { operation: 'findByIdAndDelete', id }); const lead = await Lead.findByIdAndDelete(id); if (!lead) return res.status(404).json({ success: false, message: 'Lead not found' }); console.log('[Delete Lead Response Sent]', { status: 200, deletedId: String(lead._id) }); return res.status(200).json({ success: true, deletedId: String(lead._id), message: 'Lead deleted successfully' }); } catch { return res.status(500).json({ success: false, message: 'Unable to delete lead. Please try again.' }); } });
app.patch('/api/admin/leads/:id', requireAdmin, async (req, res, next) => { try { const allowed = ['name', 'email', 'phone', 'company', 'jobTitle', 'fleetSize', 'interestedModule', 'message', 'status', 'source', 'archived']; const updates = Object.fromEntries(Object.entries(req.body || {}).filter(([key]) => allowed.includes(key))); if (updates.status && !statuses.includes(updates.status)) return res.status(400).json({ message: 'Invalid status.' }); const lead = await Lead.findById(req.params.id); if (!lead) return res.status(404).json({ message: 'Lead not found.' }); let type = 'edited'; let detail = 'Lead edited'; if (updates.status && updates.status !== lead.status) { type = 'status_changed'; detail = `Status changed from ${lead.status} to ${updates.status}`; } else if (typeof updates.archived === 'boolean' && updates.archived !== lead.archived) { type = updates.archived ? 'archived' : 'restored'; detail = updates.archived ? 'Lead archived' : 'Lead restored'; } Object.assign(lead, updates); lead.activity.push({ type, detail }); await lead.save(); res.json(safeLead(lead)); } catch (error) { next(error); } });
app.post('/api/admin/leads/:id/notes', requireAdmin, async (req, res, next) => { try { const body = String(req.body?.body || '').trim(); if (!body || body.length > 2000) return res.status(400).json({ message: 'A note between 1 and 2,000 characters is required.' }); const lead = await Lead.findByIdAndUpdate(req.params.id, { $push: { notes: { body }, activity: { type: 'note_added', detail: 'Note added' } } }, { new: true, runValidators: true }); if (!lead) return res.status(404).json({ message: 'Lead not found.' }); res.json(safeLead(lead)); } catch (error) { next(error); } });
app.patch('/api/admin/leads/:id/notes/:noteId', requireAdmin, async (req, res, next) => { try { const body = String(req.body?.body || '').trim(); if (!body || body.length > 2000) return res.status(400).json({ message: 'A note between 1 and 2,000 characters is required.' }); const lead = await Lead.findOne({ _id: req.params.id, 'notes._id': req.params.noteId }); if (!lead) return res.status(404).json({ message: 'Lead or note not found.' }); lead.notes.id(req.params.noteId).body = body; lead.activity.push({ type: 'note_edited', detail: 'Note edited' }); await lead.save(); res.json(safeLead(lead)); } catch (error) { next(error); } });
app.delete('/api/admin/leads/:id/notes/:noteId', requireAdmin, async (req, res, next) => { try { const lead = await Lead.findOne({ _id: req.params.id, 'notes._id': req.params.noteId }); if (!lead) return res.status(404).json({ message: 'Lead or note not found.' }); lead.notes.pull(req.params.noteId); lead.activity.push({ type: 'note_deleted', detail: 'Note deleted' }); await lead.save(); res.json(safeLead(lead)); } catch (error) { next(error); } });
app.get('/api/admin/leads-export', requireAdmin, async (_, res, next) => { try { const leads = await Lead.find().sort({ createdAt: -1 }); const rows = [['Booking ID', 'Name', 'Email', 'Phone', 'Company', 'Fleet size', 'Status', 'Archived', 'Created at'], ...leads.map((lead) => [lead.bookingId, lead.name, lead.email, lead.phone, lead.company, lead.fleetSize, lead.status, lead.archived, lead.createdAt.toISOString()])]; res.type('text/csv').attachment('easy-lane-leads.csv').send(rows.map((row) => row.map(csv).join(',')).join('\n')); } catch (error) { next(error); } });
app.get('/api/admin/metrics', requireAdmin, async (_, res, next) => { try { const rows = await Lead.aggregate([{ $match: { archived: false } }, { $group: { _id: '$status', count: { $sum: 1 } } }]); const metrics = Object.fromEntries(statuses.map((status) => [status, 0])); rows.forEach(({ _id, count }) => { metrics[_id] = count; }); res.json({ total: Object.values(metrics).reduce((sum, count) => sum + count, 0), ...metrics }); } catch (error) { next(error); } });
app.use('/api', (_, res) => res.status(404).json({ success: false, message: 'Route not found' }));
app.use((error, _, res, __) => { if (error?.name === 'ValidationError') return res.status(400).json({ message: Object.values(error.errors).map(({ message }) => message).join(' ') }); if (/mongoose|mongo|database|buffering/i.test(error?.message || '')) return res.status(503).json({ message: 'The database is currently unavailable. Please try again shortly.' }); console.error(error); return res.status(500).json({ message: 'Something went wrong. Please try again.' }); });
